name: deploy-react-gh-pages
on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config user.email "abraaovilanova@gmail.com"
          git config user.name "Abraão Vila Nova"

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install
      
      - name: deploy
        run: npm run deploy


